name: app_template
description: Create a Flutter App based on a standard design pattern using third-party packages for functions and features.
homepage: https://github.com/AndriousSolutions/app_template
repository: https://github.com/AndriousSolutions/app_template

version: 2.2.0+03

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # https://pub.dev/packages/dbutils
  dbutils: ^4.0.0

  # Generates English word pairs
  # https://pub.dev/packages/english_words
  english_words: ^4.0.0

  # https://pub.dev/packages/flutter_material_color_picker/
  flutter_material_color_picker: ^1.0.0

  # https://pub.dev/packages/mvc_application
  mvc_application: ^8.0.0
#      path: ../../packages/mvc_application

  # https://pub.dev/packages/i10n_translator/
  # To prevent pub publish validation error.
  i10n_translator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  assets:
    - assets/i10n/i10n.csv

    - templates/template_manifest.json
    - templates/template_manifest - Original.json
    - templates/app - Original/lib/main.dart.tmpl
    - templates/app - Original/test/widget_test.dart.tmpl
    - templates/app - Original/pubspec.yaml.tmpl
    - templates/app - Original/README.md.tmpl
    - templates/app/pubspec.yaml.tmpl
    - templates/app/README.md.tmpl
    - templates/app/assets/i10n/i10n.csv.tmpl
    - templates/app/lib/main.dart.tmpl
    - templates/app/lib/src/controller.dart.tmpl
    - templates/app/lib/src/model.dart.tmpl
    - templates/app/lib/src/view.dart.tmpl
    - templates/app/lib/src/app/controller.dart.tmpl
    - templates/app/lib/src/app/view.dart.tmpl
    - templates/app/lib/src/app/controller/theme_controller.dart.tmpl
    - templates/app/lib/src/app/controller/word_pair_timer.dart.tmpl
    - templates/app/lib/src/app/view/app.dart.tmpl
    - templates/app/lib/src/app/view/color_picker.dart.tmpl
    - templates/app/lib/src/app/view/menu/app_menu.dart.tmpl
    - templates/app/lib/src/app/view/menu/iso_spinner.dart.tmpl
    - templates/app/lib/src/home/controller.dart.tmpl
    - templates/app/lib/src/home/model.dart.tmpl
    - templates/app/lib/src/home/view.dart.tmpl
    - templates/app/lib/src/home/controller/contacts_controller.dart.tmpl
    - templates/app/lib/src/home/controller/counter_controller.dart.tmpl
    - templates/app/lib/src/home/controller/template_controller.dart.tmpl
    - templates/app/lib/src/home/controller/wordpairs_controller.dart.tmpl
    - templates/app/lib/src/home/model/settings.dart.tmpl
    - templates/app/lib/src/home/model/contacts/contact.dart.tmpl
    - templates/app/lib/src/home/model/contacts/contact_fields.dart.tmpl
    - templates/app/lib/src/home/model/contacts/contacts_db.dart.tmpl
    - templates/app/lib/src/home/model/counter/counter_model.dart.tmpl
    - templates/app/lib/src/home/model/words/wordpairs_model.dart.tmpl
    - templates/app/lib/src/home/view/contacts/add_contact.dart.tmpl
    - templates/app/lib/src/home/view/contacts/contact_details.dart.tmpl
    - templates/app/lib/src/home/view/contacts_view.dart.tmpl
    - templates/app/lib/src/home/view/counter_view.dart.tmpl

    - templates/counter_template/template_manifest.json
    - templates/counter_template/pubspec.yaml.tmpl
    - templates/counter_template/README.md.tmpl
    - templates/counter_template/app/main.dart.tmpl
    - templates/counter_template/app/lib/src/controller.dart.tmpl
    - templates/counter_template/app/lib/src/model.dart.tmpl
    - templates/counter_template/app/lib/src/view.dart.tmpl
    - templates/counter_template/app/lib/src/app/controller.dart.tmpl
    - templates/counter_template/app/lib/src/app/view.dart.tmpl
    - templates/counter_template/app/lib/src/app/controller/app_controller.dart.tmpl
    - templates/counter_template/app/lib/src/app/view/app_view.dart.tmpl
    - templates/counter_template/app/lib/src/home/controller.dart.tmpl
    - templates/counter_template/app/lib/src/home/model.dart.tmpl
    - templates/counter_template/app/lib/src/home/view.dart.tmpl
    - templates/counter_template/app/lib/src/home/controller/counter_controller.dart.tmpl
    - templates/counter_template/app/lib/src/home/model/counter_model.dart.tmpl
    - templates/counter_template/app/lib/src/home/view/counter_view.dart.tmpl

    - templates/contacts_template/app/pubspec.yaml.tmpl
    - templates/contacts_template/app/README.md.tmpl
    - templates/contacts_template/app/lib/main.dart.tmpl
    - templates/contacts_template/app/lib/src/controller.dart.tmpl
    - templates/contacts_template/app/lib/src/model.dart.tmpl
    - templates/contacts_template/app/lib/src/view.dart.tmpl
    - templates/contacts_template/app/lib/src/app/view.dart.tmpl
    - templates/contacts_template/app/lib/src/app/view/app.dart.tmpl
    - templates/contacts_template/app/lib/src/home/controller.dart.tmpl
    - templates/contacts_template/app/lib/src/home/model.dart.tmpl
    - templates/contacts_template/app/lib/src/home/view.dart.tmpl
    - templates/contacts_template/app/lib/src/home/controller/contacts_controller.dart.tmpl
    - templates/contacts_template/app/lib/src/home/model/contacts/contact.dart.tmpl
    - templates/contacts_template/app/lib/src/home/model/contacts/contact_fields.dart.tmpl
    - templates/contacts_template/app/lib/src/home/model/contacts/contacts_db.dart.tmpl
    - templates/contacts_template/app/lib/src/home/view/contacts_view.dart.tmpl
    - templates/contacts_template/app/lib/src/home/view/contacts/add_contact.dart.tmpl
    - templates/contacts_template/app/lib/src/home/view/contacts/contact_details.dart.tmpl

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
